### ISSUE TITLE
Modify BodyPix Visualizer Example

### ISSUE THREAD

**Issue by yaqqolerz** [keijiro/BodyPixSample#1]
Hello, i'm trying to modify the visualizer scene from this project. i wanted to modify the mask so instead of showing rainbow, i wanted to create particles in the shape of detected body parts similar to this video #https://www.youtube.com/watch?v=9-GiPxNZCNw
is it possible? thanks

**Comment by keijiro** [comment]
yes https://github.com/keijiro/NNCam2

**Comment by yaqqolerz** [comment]
is there any guide in using this? i tried using keyboard buttons and the only buttons working are Q,W,1,2,3
and also is it possible to bind it to other key? thanks a lot!
