### ISSUE TITLE
Android and WebGL build issues

### ISSUE THREAD

**Issue by suyashcjoshi** [keijiro/BodyPixSample#2]
Love this sample app, thank you so much for creating it. However wondering if I can request a simpler version without Shader Graph stuff as the Android build is running terribly slow and the WebGL build is totally crashing due to poor / no support of Compute Shader in WebGL and Android.

**Comment by keijiro** [comment]
Samples without shader graphs.

https://github.com/keijiro/BodyPixBarracuda

>  the Android build is running terribly slow and the WebGL build is totally crashing due to poor / no support of Compute Shader in WebGL and Android.

Those issue are not relevant to Shader Graph.
